### ISSUE TITLE
问下能在pve的shell下运行吗？

### ISSUE THREAD

**Issue by jinwyp** [Cyberpunk2177/AcuteAngle#2]
问下能在pve的shell下运行吗？  不在 uefi built in efi shell 下运行

例如把 bootx64.efi 复制到pve的shell下 /root/bootx64.efi  
如果能运行应该怎么运行 ？ 

setup_var_3 这个文件哪里来的？能在pve的shell下运行吗？

我想做个一键脚本解决安装问题

**Comment by unsciorg** [comment]
Nope

JinWYP ***@***.***> 于2021年2月10日周三 上午11:04写道：
