### ISSUE TITLE
黑屏BOOM，BIOS进不去

### ISSUE THREAD

**Issue by now163** [Cyberpunk2177/AcuteAngle#5]
在PVE下修改成功了。使用政策。
但随后重装成win10，机器就在也起不来了。。

**Comment by unsciorg** [comment]
如果不幸boom了，可以断电十分钟左右就会恢复的，或者拔下BIOS电池也可以

**Comment by now163** [comment]
不好使，不确定是修改的事，还是机器本身出了问题。开机风扇和usb口都有电，但就是黑屏。砖头了。。。 :(

**Comment by unsciorg** [comment]
> 

那大抵是真的BOOM了，可以试试拔下主板电池（如果有，然后放十天半个月的
