### ISSUE TITLE
自动版在OMV7上运行成功

### ISSUE THREAD

**Issue by MasterOfStar** [Cyberpunk2177/AcuteAngle#7]
自动版在OMV7上运行成功 omv7 based debian12 所以看起来至少在debian系上面应该都能成功

**Comment by unsciorg** [comment]
都2402年了怎么还有人在晚这个。。。

**Comment by MasterOfStar** [comment]
> 都2402年了怎么还有人在晚这个。。。

床底下翻出来的 吃了好久灰
